name: Trigger Jenkins Job

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger on

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    env:
      JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}

    steps:
    - name: Trigger Jenkins Job
      run: |
        curl -X POST "https://devops.jenkins.cnvrg.io/job/QA-IDC-API/build" \
          --user "$JENKINS_USERNAME:$JENKINS_API_TOKEN"
