name: Trigger Jenkins Job

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger on

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    env:
      JENKINS_COOKIE: ${{ secrets.JENKINS_COOKIE }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}

    steps:
    - name: Trigger Jenkins Job
      run: |
        echo "My secret API key: $JENKINS_COOKIE"
        # curl 'https://devops.jenkins.cnvrg.io/job/QA-IDC-API/buildWithParameters?token=$JENKINS_API_TOKEN' \
        # -H 'Cookie: $JENKINS_COOKIE'
